# Generated by Django 4.0 on 2021-12-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kigurumi',
            name='id',
        ),
        migrations.AddField(
            model_name='kigurumi',
            name='img',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='kigurumi',
            name='name',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kigurumi',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kigurumi',
            name='sizes',
            field=models.CharField(default='', max_length=100),
        ),
    ]
