# Generated by Django 4.0 on 2021-12-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_kigurumi_id_alter_kigurumi_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kigurumi',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
