# Generated by Django 4.0 on 2022-01-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_kigurumi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(default='', max_length=100)),
                ('region', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=300)),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=100)),
                ('kigurumi_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
